spring:
  main:
    banner-mode: off

  datasource:
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    driver-class-name: org.postgresql.Driver

  jpa:
    defer-datasource-initialization: false
    open-in-view: false

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

jwt:
  secret: 456ba88f089978bc757f6cfebf7e790d1fe268ff876302e576ee23e82b31e89c

