spring:
  main:
    banner-mode: off

  datasource:
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    driver-class-name: org.postgresql.Driver

  jpa:
    defer-datasource-initialization: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
    drop-first: true




