spring:
  main:
    banner-mode: off

  datasource:
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USER}
    driver-class-name: org.postgresql.Driver

  jpa:
    defer-datasource-initialization: false
    open-in-view: false
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
    drop-first: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com
          auth: true

  thymeleaf:
    prefix: classpath:templates/
    suffix: .html

jwt:
  secret: ${JWT_SECRET_KEY}